#TODO: figure out why I need this here and in bootstrap.yml
spring:
  application:
    name: testLatticeApp

http:
  port: 80
server:
  port: 443
  ssl:
    key-store: classpath:4627742_www.dealfuns.com.pfx
    key-store-password: cIEzsCMt
    keyStoreType: PKCS12

ribbon:
  ServerListRefreshInterval: 1000

endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true